/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElButton: typeof import('element-plus-secondary/es')['ElButton']
  const ElCheckbox: typeof import('element-plus-secondary/es')['ElCheckbox']
  const ElDatePicker: typeof import('element-plus-secondary/es')['ElDatePicker']
  const ElInput: typeof import('element-plus-secondary/es')['ElInput']
  const ElMessage: typeof import('element-plus-secondary/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus-secondary/es')['ElMessageBox']
  const ElRadio: typeof import('element-plus-secondary/es')['ElRadio']
  const ElRadioGroup: typeof import('element-plus-secondary/es')['ElRadioGroup']
  const ElSelect: typeof import('element-plus-secondary/es')['ElSelect']
  const LicenseGenerator: any
}
