"""P2 音频资产、语音用量与音色试听字段

Revision ID: 174f554d68d9
Revises: b41d7a90c5e2
Create Date: 2026-09-13 00:42:23.512625

两张新表 + 音色档案两列，都是**纯新增**：没有改列、没有换约束、没有数据搬运，
所以这一版不像 P1 那条迁移需要整表重建，加列即可（SQLite 支持 ADD COLUMN）。

几处值得写下来的决定：

1. `audio_assets.course_id` 有外键且 `ON DELETE CASCADE` —— 它是**缓存索引**，
   课程行没了，索引指向的文件也没有意义（P2-C2）。注意 P1 的删除是软删，
   所以这条级联只在真正清理数据时才触发。
2. `usage_records.ref_id` / `audio_assets.voice_id` **不建外键**：
   账本不随业务数据消失（与 model_calls 同理），而音频行留着还能在音色加回来时命中缓存。
3. `file_path` 存相对路径且长度给到 255（P2-C4）：绝对路径换机器就全废，
   而 `data/assets/audio/{course_id}/{beat_id}_{hash8}.mp3` 最长的组合也不会撑满。
4. 降级只删表，**不删磁盘上的音频文件** —— 迁移不该动文件系统。
   真要清干净走服务层的清理入口（P2-C2），那是有日志、可断言的动作。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174f554d68d9'
down_revision = 'b41d7a90c5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=16), nullable=False),
    sa.Column('est_cost', sa.Float(), nullable=False),
    sa.Column('ref_type', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('tts', 'realtime', 'asr')", name=op.f('ck_usage_records_usage_record_kind_valid')),
    sa.CheckConstraint("ref_type IN ('course', 'session')", name=op.f('ck_usage_records_usage_record_ref_type_valid')),
    sa.CheckConstraint("unit_name IN ('chars', 'seconds')", name=op.f('ck_usage_records_usage_record_unit_name_valid')),
    sa.CheckConstraint('est_cost >= 0', name=op.f('ck_usage_records_usage_record_cost_non_negative')),
    sa.CheckConstraint('units >= 0', name=op.f('ck_usage_records_usage_record_units_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records'))
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_records_created', ['created_at'], unique=False)
        batch_op.create_index('ix_usage_records_kind_created', ['kind', 'created_at'], unique=False)
        batch_op.create_index('ix_usage_records_ref', ['ref_type', 'ref_id'], unique=False)

    op.create_table('audio_assets',
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.String(length=32), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('voice_id', sa.String(length=32), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('ready', 'stale', 'failed')", name=op.f('ck_audio_assets_audio_asset_status_valid')),
    sa.CheckConstraint("file_path IS NULL OR (file_path LIKE 'data/assets/audio/%' AND file_path NOT LIKE '%..%')", name=op.f('ck_audio_assets_audio_asset_file_path_relative')),
    sa.CheckConstraint('duration_ms >= 0', name=op.f('ck_audio_assets_audio_asset_duration_non_negative')),
    sa.CheckConstraint('page_no > 0', name=op.f('ck_audio_assets_audio_asset_page_no_positive')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_audio_assets_audio_asset_size_non_negative')),
    sa.CheckConstraint('speed >= -50 AND speed <= 100', name=op.f('ck_audio_assets_audio_asset_speed_in_range')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_audio_assets_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_assets')),
    sa.UniqueConstraint('course_id', 'beat_id', 'voice_id', 'speed', 'tone', name='uq_audio_assets_beat_voice')
    )
    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.create_index('ix_audio_assets_course_page', ['course_id', 'page_no'], unique=False)

    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('params_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.drop_column('params_json')
        batch_op.drop_column('preview_url')

    with op.batch_alter_table('audio_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_audio_assets_course_page')

    op.drop_table('audio_assets')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_records_ref')
        batch_op.drop_index('ix_usage_records_kind_created')
        batch_op.drop_index('ix_usage_records_created')

    op.drop_table('usage_records')
    # ### end Alembic commands ###
