"""P0 initial schema: users/settings_kv/providers/voice_profiles/agent_roles/courses/course_pages

Revision ID: 3375f280213f
Revises: 
Create Date: 2026-09-12 16:29:05.248924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3375f280213f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('api_key_enc', sa.Text(), nullable=True),
    sa.Column('default_model', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('llm', 'tts', 'asr')", name=op.f('ck_providers_provider_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_table('settings_kv',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings_kv'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('avatar_color', sa.String(length=16), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("role IN ('teacher', 'student', 'admin')", name=op.f('ck_users_user_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('voice_profiles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('voice_type', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('style', sa.String(length=128), nullable=True),
    sa.Column('sample_url', sa.String(length=255), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('speech_rate', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female', 'neutral')", name=op.f('ck_voice_profiles_voice_gender_valid')),
    sa.CheckConstraint("provider IN ('volc_tts', 'volc_realtime', 'browser')", name=op.f('ck_voice_profiles_voice_provider_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_profiles'))
    )
    op.create_table('agent_roles',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('avatar_color', sa.String(length=16), nullable=True),
    sa.Column('persona_json', sa.Text(), nullable=True),
    sa.Column('voice_profile_id', sa.String(length=32), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("role IN ('teacher', 'student')", name=op.f('ck_agent_roles_agent_role_valid')),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], name=op.f('fk_agent_roles_voice_profile_id_voice_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_agent_roles_code'))
    )
    op.create_table('courses',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('cover_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('dsl_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'generating', 'ready', 'failed')", name=op.f('ck_courses_course_status_valid')),
    sa.CheckConstraint('page_count >= 0', name=op.f('ck_courses_course_page_count_non_negative')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_courses_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('ix_courses_owner_status', ['owner_id', 'status'], unique=False)

    op.create_table('course_pages',
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dsl_json', sa.Text(), nullable=True),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('cover', 'content', 'quiz', 'summary')", name=op.f('ck_course_pages_course_page_kind_valid')),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed')", name=op.f('ck_course_pages_course_page_status_valid')),
    sa.CheckConstraint('page_no > 0', name=op.f('ck_course_pages_course_page_no_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_pages_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_pages')),
    sa.UniqueConstraint('course_id', 'page_no', name='uq_course_pages_course_page')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_pages')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index('ix_courses_owner_status')

    op.drop_table('courses')
    op.drop_table('agent_roles')
    op.drop_table('voice_profiles')
    op.drop_table('users')
    op.drop_table('settings_kv')
    op.drop_table('providers')
    # ### end Alembic commands ###
