"""P1 generation jobs, steps, events, page versions, model_calls, audit_logs

Revision ID: 93066cfa72dd
Revises: 3375f280213f
Create Date: 2026-09-12 19:02:13.575312

除了六张新表，这一版还干了一件 Alembic 自动生成看不出来的事：
把 `course_pages.kind` 的 CHECK 从 P0 的四个占位值
(cover/content/quiz/summary) 换成 P1 §3.2 的九种页型。

为什么不是一句 batch_alter_table 就完事 —— 这里有个双向都会踩的坑：

    P0 约束只允许 content，P1 约束只允许 concept，两个集合不相交。
    任何「先 UPDATE 数据、再换约束」的顺序，都会被**当前生效**的那条约束拦下：
    升级时写 concept 违反旧约束，降级时写 content 违反新约束。

所以数据映射必须与表重建**在同一条语句里**完成 —— 建新表时用 CASE 把
非法值就地收敛成合法值再插入。SQLite 也没有 ALTER CHECK，整表重建是唯一路径。

顺带一提：契约测试从空库开始，抓不到这个坑；只有拿一个真装了 P0 数据的库
跑一遍才会暴露（本迁移就是这么验的）。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93066cfa72dd'
down_revision = '3375f280213f'
branch_labels = None
depends_on = None

#: P1 §3.2 的九种页型（与 app/models/course.py 的 PAGE_KINDS 必须一致）
_PAGE_KINDS_P1 = (
    "'cover', 'outline', 'concept', 'figure', 'example',"
    " 'code', 'quiz', 'summary', 'debate'"
)
_PAGE_KINDS_P0 = "'cover', 'content', 'quiz', 'summary'"

#: 两个版本都认的页型 —— 只有这几个能在重建时原样带过去，
#: 其余的一律收敛成该方向的对应物（升级 content→concept，降级 →content）。
_SHARED_KINDS = "'cover', 'quiz', 'summary'"

#: 迁移里显式写死列清单，不引用当前模型 —— 迁移描述的是「那一刻的表结构」，
#: 跟着模型走会让历史版本随模型演进而变样，回放就不再可复现。
_COLUMNS = (
    "id", "course_id", "chapter_no", "page_no", "kind", "title",
    "status", "dsl_json", "rev", "created_at", "updated_at",
)


def _course_pages(kinds_sql: str, name: str) -> sa.Table:
    """某个版本下 course_pages 的结构。name 用于建临时表。"""
    metadata = sa.MetaData()
    # 外键的目标表要在这个 MetaData 里认得出来，否则建表时解析不了 courses.id。
    # 只声明主键列：这里只是给 FK 一个落点，不会真的去建它。
    sa.Table("courses", metadata, sa.Column("id", sa.String(32), primary_key=True))
    return sa.Table(
        name,
        metadata,
        sa.Column("id", sa.String(32), primary_key=True),
        sa.Column("course_id", sa.String(32), nullable=False),
        sa.Column("chapter_no", sa.Integer(), nullable=False),
        sa.Column("page_no", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("title", sa.String(255)),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("dsl_json", sa.Text()),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(32), nullable=False),
        sa.Column("updated_at", sa.String(32), nullable=False),
        sa.CheckConstraint("page_no > 0", name="ck_course_pages_course_page_no_positive"),
        sa.CheckConstraint(
            f"kind IN ({kinds_sql})", name="ck_course_pages_course_page_kind_valid"
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'failed')",
            name="ck_course_pages_course_page_status_valid",
        ),
        sa.UniqueConstraint("course_id", "page_no", name="uq_course_pages_course_page"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name="fk_course_pages_course_id_courses",
            ondelete="CASCADE",
        ),
    )


def _rebuild_course_pages(kinds_sql: str, allowed: str, fallback: str) -> None:
    """把 course_pages 重建成 kinds_sql 约束的表。

    入参 allowed 是「新约束下依然合法、可以原样搬过去」的取值集合
    （即新旧两个页型表的交集），其余一律收敛为 fallback。
    """
    tmp = "course_pages_rebuild"
    op.execute(f'DROP TABLE IF EXISTS "{tmp}"')
    _course_pages(kinds_sql, tmp).create(bind=op.get_bind())

    columns = ", ".join(_COLUMNS)
    op.get_bind().execute(
        sa.text(
            f'INSERT INTO "{tmp}" ({columns}) SELECT '
            f"id, course_id, chapter_no, page_no, "
            f"CASE WHEN kind IN ({allowed}) THEN kind ELSE :fallback END, "
            f"title, status, dsl_json, rev, created_at, updated_at "
            f"FROM course_pages"
        ),
        {"fallback": fallback},
    )
    op.drop_table("course_pages")
    op.rename_table(tmp, "course_pages")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)

    op.create_table('model_calls',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=32), nullable=True),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('llm', 'tts', 'asr', 'realtime')", name=op.f('ck_model_calls_model_call_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_calls'))
    )
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.create_index('ix_model_calls_created', ['created_at'], unique=False)
        batch_op.create_index('ix_model_calls_job', ['job_id'], unique=False)

    op.create_table('gen_jobs',
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'paused', 'done', 'failed', 'canceled')", name=op.f('ck_gen_jobs_gen_job_status_valid')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_gen_jobs_gen_job_progress_in_range')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_gen_jobs_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_gen_jobs_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gen_jobs'))
    )
    with op.batch_alter_table('gen_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_gen_jobs_course', ['course_id'], unique=False)
        batch_op.create_index('ix_gen_jobs_owner_status', ['owner_id', 'status'], unique=False)

    op.create_table('course_page_versions',
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('dsl_json', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=16), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("reason IN ('generate', 'rewrite', 'manual')", name=op.f('ck_course_page_versions_course_page_version_reason_valid')),
    sa.CheckConstraint('rev > 0', name=op.f('ck_course_page_versions_course_page_version_rev_positive')),
    sa.ForeignKeyConstraint(['page_id'], ['course_pages.id'], name=op.f('fk_course_page_versions_page_id_course_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_page_versions')),
    sa.UniqueConstraint('page_id', 'rev', name='uq_course_page_versions_page_rev')
    )
    op.create_table('gen_events',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['gen_jobs.id'], name=op.f('fk_gen_events_job_id_gen_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gen_events')),
    sa.UniqueConstraint('job_id', 'seq', name='uq_gen_events_job_seq')
    )
    op.create_table('gen_steps',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('finished_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('wait', 'running', 'done', 'failed', 'skipped')", name=op.f('ck_gen_steps_gen_step_status_valid')),
    sa.CheckConstraint("type IN ('parse', 'outline', 'write', 'quiz', 'tts', 'assemble')", name=op.f('ck_gen_steps_gen_step_type_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['gen_jobs.id'], name=op.f('fk_gen_steps_job_id_gen_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gen_steps')),
    sa.UniqueConstraint('job_id', 'seq', name='uq_gen_steps_job_seq')
    )

    # --- course_pages.kind：四个占位页型 → 九种 P1 页型 ---
    # content 是 P0 的通用内容页，P1 里这个位置由 concept 承担，就地改名。
    _rebuild_course_pages(_PAGE_KINDS_P1, _SHARED_KINDS, "concept")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 反向：P1 独有的页型（outline/figure/example/code/debate）在 P0 没有对应物，
    # 统一收敛回 content —— 降级是有损的，但不该失败，也不该删数据。
    _rebuild_course_pages(_PAGE_KINDS_P0, _SHARED_KINDS, "content")

    op.drop_table('gen_steps')
    op.drop_table('gen_events')
    op.drop_table('course_page_versions')
    with op.batch_alter_table('gen_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_gen_jobs_owner_status')
        batch_op.drop_index('ix_gen_jobs_course')

    op.drop_table('gen_jobs')
    with op.batch_alter_table('model_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_model_calls_job')
        batch_op.drop_index('ix_model_calls_created')

    op.drop_table('model_calls')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_action_created')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
