"""P3 课堂运行时：会话/参与者/事件/消息/举手/作答/板书 七张表

Revision ID: d44ccaf4af9c
Revises: 174f554d68d9
Create Date: 2026-09-13 02:58:48.670181

七张新表，**纯新增**：不改任何既有列，所以不像 P1 那两条迁移要整表重建。

几处值得写下来的决定：

1. **级联分两层**：`courses → classroom_sessions`（P3-C4：删课不留孤儿课），
   以及 `classroom_sessions → 其余六张`（下课时清一次会话，六张子表跟着走）。
   两层的 `ON DELETE CASCADE` 都**靠 `PRAGMA foreign_keys=ON` 生效**（同 P1-C3），
   不是靠 ORM 逐个删 —— 那会让「一句 DELETE 清掉一堂课」变成 N 次查询。
2. **`session_events(session_id, seq)` 唯一**，不只是索引（P3-B2）。补发是
   「给我 seq > N 的」，去重是「同一个 seq 只认一次」；约束在库里，就不必靠
   应用层记得别写重。代价是分配 `seq` 必须单写者 —— 这正是 §2.2 的要求，
   两边是同一件事的两面。
3. **`session_events` 没有 `updated_at`**（只有 `created_at`）：事件写下去就不会变，
   多一列只会让人以为它可以改。其余六张都有，因为它们的行确实会被更新
   （会话推进、参与者上下线、举手被点名、消息补音频地址）。
4. **约束列没有 `server_default`**：默认值一律在模型层（Python 端 `default=`），
   与既有六条迁移一致。这意味着**裸 SQL 的 INSERT 必须显式给值**，
   NOT NULL 会挡住它 —— 这是有意的：课堂状态只能由服务层写。
5. **两处索引比 §5 多**：`classroom_sessions(course_id, status)` 与
   `(owner_id, started_at)`（「这门课还有课在跑吗」「我最近开的课」），
   以及 `quiz_attempts` 的两条（P6.1 学情聚合按课程/页面取数）。
   都是真实读路径，不是预防性加的。
6. 降级只删表、**不删磁盘上的东西**（同 P2）：迁移不动文件系统。
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44ccaf4af9c'
down_revision = '174f554d68d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_sessions',
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_page_no', sa.Integer(), nullable=False),
    sa.Column('current_beat_idx', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('started_at', sa.String(length=32), nullable=True),
    sa.Column('ended_at', sa.String(length=32), nullable=True),
    sa.Column('state_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("mode IN ('auto', 'manual')", name=op.f('ck_classroom_sessions_classroom_session_mode_valid')),
    sa.CheckConstraint("status IN ('idle', 'lecture', 'discussing', 'quiz_wait', 'board_show', 'paused', 'ended')", name=op.f('ck_classroom_sessions_classroom_session_status_valid')),
    sa.CheckConstraint('current_beat_idx >= 0', name=op.f('ck_classroom_sessions_classroom_session_beat_non_negative')),
    sa.CheckConstraint('current_page_no > 0', name=op.f('ck_classroom_sessions_classroom_session_page_positive')),
    sa.CheckConstraint('speed > 0', name=op.f('ck_classroom_sessions_classroom_session_speed_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_classroom_sessions_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_classroom_sessions_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classroom_sessions'))
    )
    with op.batch_alter_table('classroom_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_classroom_sessions_course_status', ['course_id', 'status'], unique=False)
        batch_op.create_index('ix_classroom_sessions_owner_started', ['owner_id', 'started_at'], unique=False)

    op.create_table('board_strokes',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('stroke_no', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('points_json', sa.Text(), nullable=True),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('at_beat_id', sa.String(length=32), nullable=True),
    sa.Column('dur_ms', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("author IN ('teacher', 'me')", name=op.f('ck_board_strokes_stroke_author_valid')),
    sa.CheckConstraint("tool IN ('polyline', 'curve', 'text', 'arrow', 'rect', 'ellipse')", name=op.f('ck_board_strokes_stroke_tool_valid')),
    sa.CheckConstraint('dur_ms >= 0', name=op.f('ck_board_strokes_stroke_duration_non_negative')),
    sa.CheckConstraint('page_no > 0', name=op.f('ck_board_strokes_stroke_page_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_board_strokes_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], name=op.f('fk_board_strokes_session_id_classroom_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_strokes'))
    )
    with op.batch_alter_table('board_strokes', schema=None) as batch_op:
        batch_op.create_index('ix_board_strokes_course_page', ['course_id', 'page_no', 'stroke_no'], unique=False)
        batch_op.create_index('ix_board_strokes_session', ['session_id', 'page_no'], unique=False)

    op.create_table('hand_queue',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('called_at', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'called', 'done', 'canceled')", name=op.f('ck_hand_queue_hand_status_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], name=op.f('fk_hand_queue_session_id_classroom_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_hand_queue_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hand_queue'))
    )
    with op.batch_alter_table('hand_queue', schema=None) as batch_op:
        batch_op.create_index('ix_hand_queue_session_status', ['session_id', 'status'], unique=False)

    op.create_table('messages',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('speaker_code', sa.String(length=32), nullable=False),
    sa.Column('speaker_kind', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('beat_id', sa.String(length=32), nullable=True),
    sa.Column('audio_url', sa.String(length=255), nullable=True),
    sa.Column('quote_msg_id', sa.String(length=32), nullable=True),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("speaker_kind IN ('teacher', 'student_ai', 'me', 'system')", name=op.f('ck_messages_message_speaker_kind_valid')),
    sa.CheckConstraint("type IN ('lecture', 'question', 'supplement', 'reflect', 'answer', 'comment', 'system')", name=op.f('ck_messages_message_type_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], name=op.f('fk_messages_session_id_classroom_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_session_ts', ['session_id', 'ts'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('option', sa.String(length=16), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('ts', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint('page_no > 0', name=op.f('ck_quiz_attempts_quiz_attempt_page_positive')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_quiz_attempts_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], name=op.f('fk_quiz_attempts_session_id_classroom_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_quiz_attempts_course_page', ['course_id', 'page_no'], unique=False)
        batch_op.create_index('ix_quiz_attempts_session_page', ['session_id', 'page_no'], unique=False)

    op.create_table('session_events',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], name=op.f('fk_session_events_session_id_classroom_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_events')),
    sa.UniqueConstraint('session_id', 'seq', name='uq_session_events_session_seq')
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index('ix_session_events_session_type', ['session_id', 'type'], unique=False)

    op.create_table('session_participants',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.String(length=32), nullable=False),
    sa.Column('left_at', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_session_participants_participant_role_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['classroom_sessions.id'], name=op.f('fk_session_participants_session_id_classroom_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_participants_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_participants')),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_participants_session_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_participants')
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index('ix_session_events_session_type')

    op.drop_table('session_events')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_attempts_session_page')
        batch_op.drop_index('ix_quiz_attempts_course_page')

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_session_ts')

    op.drop_table('messages')
    with op.batch_alter_table('hand_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_hand_queue_session_status')

    op.drop_table('hand_queue')
    with op.batch_alter_table('board_strokes', schema=None) as batch_op:
        batch_op.drop_index('ix_board_strokes_session')
        batch_op.drop_index('ix_board_strokes_course_page')

    op.drop_table('board_strokes')
    with op.batch_alter_table('classroom_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_classroom_sessions_owner_started')
        batch_op.drop_index('ix_classroom_sessions_course_status')

    op.drop_table('classroom_sessions')
    # ### end Alembic commands ###
