knowledge-base.refs=group,biz

knowledge-base.group.name=集团信息化
knowledge-base.group.collection-name=tutorial_group
knowledge-base.group.embedding-model=qwen-emb-8b
knowledge-base.group.documents=docs/knowledge/group

knowledge-base.biz.name=业务系统
knowledge-base.biz.collection-name=tutorial_biz
knowledge-base.biz.embedding-model=qwen-emb-8b
knowledge-base.biz.documents=docs/knowledge/biz
