"""015_modify_chat

Revision ID: 02d84523a979
Revises: fde8acca6143
Create Date: 2025-06-25 15:45:14.968598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02d84523a979'
down_revision = 'fde8acca6143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'datasource',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'datasource',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
