"""034_field_sort

Revision ID: e8b470d2b150
Revises: 3cb5d6a54f2e
Create Date: 2025-08-08 11:33:33.227564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8b470d2b150'
down_revision = '3cb5d6a54f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_field', sa.Column('field_index', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_field', 'field_index')
    # ### end Alembic commands ###
