"""044_table_relation

Revision ID: 455b8ce69e80
Revises: dac062c1f7b1
Create Date: 2025-09-24 13:34:08.205659

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '455b8ce69e80'
down_revision = 'dac062c1f7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_datasource', sa.Column('table_relation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_datasource', 'table_relation')
    # ### end Alembic commands ###
