"""045_modify_terminolog

Revision ID: 45e7e52bf2b8
Revises: 455b8ce69e80
Create Date: 2025-09-25 14:49:24.521795

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45e7e52bf2b8'
down_revision = '455b8ce69e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terminology', sa.Column('specific_ds', sa.Boolean(), nullable=True))
    op.add_column('terminology', sa.Column('datasource_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminology', 'datasource_ids')
    op.drop_column('terminology', 'specific_ds')
    # ### end Alembic commands ###
