"""046_add_custom_prompt

Revision ID: 8855aea2dd61
Revises: 45e7e52bf2b8
Create Date: 2025-09-28 13:57:01.509249

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8855aea2dd61'
down_revision = '45e7e52bf2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_prompt',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('oid', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('GENERATE_SQL', 'ANALYSIS', 'PREDICT_DATA', name='customprompttypeenum', native_enum=False, length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('specific_ds', sa.Boolean(), nullable=True),
    sa.Column('datasource_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_prompt')
    # ### end Alembic commands ###
