"""047_table_embedding

Revision ID: c1b794a961ce
Revises: 8855aea2dd61
Create Date: 2025-10-09 11:32:10.578313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1b794a961ce'
down_revision = '8855aea2dd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_table', sa.Column('embedding', sa.Text(), nullable=True))
    op.add_column('core_datasource', sa.Column('embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_table', 'embedding')
    op.drop_column('core_datasource', 'embedding')
    # ### end Alembic commands ###
