"""048_authentication_ddl

Revision ID: 073bf544b373
Revises: c1b794a961ce
Create Date: 2025-10-30 14:11:29.786938

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '073bf544b373'
down_revision = 'c1b794a961ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_authentication',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(255), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_authentication_id'), 'sys_authentication', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_authentication_id'), table_name='sys_authentication')
    op.drop_table('sys_authentication')
    # ### end Alembic commands ###
