"""051_modify_data_training_ddl

Revision ID: cb12c4238120
Revises: 2785e54dc1c4
Create Date: 2025-11-10 16:11:29.753516

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb12c4238120'
down_revision = '2785e54dc1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_training', sa.Column('advanced_application', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_training', 'advanced_application')
    # ### end Alembic commands ###
