"""054_update_chat_record_dll

Revision ID: 24e961f6326b
Revises: 5755c0b95839
Create Date: 2025-12-04 15:51:42.900778

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24e961f6326b'
down_revision = '5755c0b95839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_record', sa.Column('regenerate_record_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_record', 'regenerate_record_id')
    # ### end Alembic commands ###
