"""056_api_key_ddl

Revision ID: d9a5589fc00b
Revises: 3d4bd2d673dc
Create Date: 2025-12-23 13:41:26.705947

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9a5589fc00b'
down_revision = '3d4bd2d673dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_apikey',
    sa.Column('access_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('create_time', sa.BigInteger(), nullable=False),
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_apikey_id'), 'sys_apikey', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_apikey_id'), table_name='sys_apikey')
    op.drop_table('sys_apikey')
    # ### end Alembic commands ###
