"""empty message

Revision ID: db1a95567cbb
Revises: fb2e8dd19158
Create Date: 2025-12-30 12:29:14.290394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db1a95567cbb'
down_revision = 'fb2e8dd19158'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('sys_logs_resource',
                    sa.Column('id', sa.BIGINT(),
                              sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=999999999999999,
                                          cycle=False, cache=1), autoincrement=True, nullable=False),
                    sa.Column('resource_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('module', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('resource_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('log_id', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('sys_logs_resource_pkey'))
                    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_logs_resource')
    # ### end Alembic commands ###
