"""061_assistant_oid_ddl

Revision ID: 547df942eb90
Revises: b40e41c67db3
Create Date: 2026-01-09 15:02:19.891766

"""
import json
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '547df942eb90'
down_revision = 'b40e41c67db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('sys_assistant', sa.Column('oid', sa.BigInteger(), nullable=True))
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE sys_assistant SET oid = 1 WHERE oid IS NULL"))
    rows = conn.execute(
        sa.text("SELECT id, configuration FROM sys_assistant WHERE type = 0 AND configuration IS NOT NULL")
    )
    for row in rows:
        try:
            config = json.loads(row.configuration) if isinstance(row.configuration, str) else row.configuration
            oid_value = config.get('oid', 1) if isinstance(config, dict) else 1
            if oid_value != 1:
                if not isinstance(oid_value, int):
                    oid_value = int(oid_value)
                conn.execute(
                    sa.text("UPDATE sys_assistant SET oid = :oid WHERE id = :id"),
                    {"oid": oid_value, "id": row.id}
                )
        except (json.JSONDecodeError, TypeError, AttributeError):
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_assistant', 'oid')
    # ### end Alembic commands ###
