"""062_update_chat_log_dll

Revision ID: c9ab05247503
Revises: 547df942eb90
Create Date: 2026-01-27 14:20:35.069255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9ab05247503'
down_revision = '547df942eb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('local_operation', sa.Boolean(), nullable=True))
    sql = '''
    UPDATE chat_log SET local_operation = false
    '''
    op.execute(sql)
    op.alter_column('chat_log', 'local_operation',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_log', 'local_operation')
    # ### end Alembic commands ###
