"""063_update_chat_log_dll

Revision ID: c8751179a8de
Revises: c9ab05247503
Create Date: 2026-01-29 14:41:21.022781

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8751179a8de'
down_revision = 'c9ab05247503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_log', sa.Column('error', sa.Boolean(), nullable=True))
    sql = '''
    UPDATE chat_log SET error = false
    '''
    op.execute(sql)
    op.alter_column('chat_log', 'error',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_log', 'error')
    # ### end Alembic commands ###
