"""066_update_assistant_model

Revision ID: 8adc3a4919be
Revises: 8ff90df7871d
Create Date: 2026-04-28 15:55:42.757276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8adc3a4919be'
down_revision = '8ff90df7871d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_assistant', sa.Column('enable_custom_model', sa.Boolean(), nullable=True))
    op.add_column('sys_assistant', sa.Column('custom_model', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('sys_assistant', 'custom_model')
    op.drop_column('sys_assistant', 'enable_custom_model')
    # ### end Alembic commands ###
