"""067_ai_model_workspace_mapping

Revision ID: e51127e9aa4a
Revises: 8adc3a4919be
Create Date: 2026-06-01 14:14:23.112843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e51127e9aa4a'
down_revision = '8adc3a4919be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_workspace_mapping',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ai_model_id', sa.BigInteger(), nullable=True),
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_model_workspace_mapping')
    # ### end Alembic commands ###
