"""069_term_custom_prompt

Revision ID: 1f82cad3546e
Revises: a1b2c3d4e5f6
Create Date: 2026-06-15 14:51:12.280391

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f82cad3546e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_prompt', sa.Column('advanced_application', sa.BigInteger(), nullable=True))
    op.add_column('terminology', sa.Column('advanced_application', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terminology', 'advanced_application')
    op.drop_column('custom_prompt', 'advanced_application')
    # ### end Alembic commands ###
