"""071_modify_permission_jsonb

Revision ID: a2e2ecfa5a9c
Revises: 070a1b2c3d4e5
Create Date: 2026-07-16 16:56:47.093944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2e2ecfa5a9c'
down_revision = '070a1b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ds_rules', 'permission_list',
                    existing_type=sa.Text(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True,
                    postgresql_using='permission_list::jsonb')
    op.alter_column('ds_rules', 'user_list',
                    existing_type=sa.Text(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=True,
                    postgresql_using='user_list::jsonb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ds_rules', 'permission_list',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.Text(),
                    existing_nullable=True)
    op.alter_column('ds_rules', 'user_list',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###
